language: node_js
cache: yarn
node_js:
- '8.4'
script:
- yarn run validate
- yarn run test
# Currently disabled travis deploys
# deploy:
#   provider: npm
#   email: alexreardon@gmail.com
# # avoid removing node modules before publish step (needed to run commands!)
#   skip_cleanup: true
#   api_key:
#     secure: qqKc08HEhgqauJI6tGP/DIxSRIttPsQCuXjhSp/1VoU6H9Ye0IvJo9h3IQcrxdMF1+d8YSqT9tLzGQTjyOgUTjKe1Mgstyd4ShMBPBWWsF0PyT0Hnhn+NL4e+sWycu6RQdevWy4GFQ1gTYrTXIW9Gv+joUVua9RE7fZJPX0pAShiDTn3U/SOviWegBba9VrIN1e3GX3pZ+aHKq8Ns9EhlT/yfpipAnIQt4FOw11s+4+MZ9VyhL8B3pJ2QzeZ5DpIIsQJ/JPiLM/UZGwGltU+Fdz95Znf7MtH/2kwXv7vnwwdBDVKV92fyJUDmuU5UjBXGOPf7OYSBE/rfSMd80xYzrkTkWCBuCQ1l4WFDfGaOKhOJzZW1w0evZFLmlUnYz07Qg8/UbfIvfd5DUud7HsC74cUEBkshTyrE9kbi6ZBe2Qi1Yp9z+zvafnEfPyJbkNgsmf5bQ+VsKdUGpy3XLKwxIly7BLkj5LtCBtGNjIaPPCJ4w/kCGfjWntOyPc4gkHfrOG0N6w8wqqCyL01NOhbz0eH3mGQjdGSvn27EbjodChfQRWWysGxoCWZAS69zvQvs5qglK3yjMIaaW1oKEtRah8D4j1DZCty8H+2fQLH0U1AwfGm+4uYuMXPPz+wSuajmJOlG995wLJeVnIzmai2kE22N6oEvbVbVsATOIdurjY=
#   on:
#     branch: master
#     tags: true
#     repo: atlassian/react-beautiful-dnd
# Used for updating lock file
env:
  global:
    secure: CfvbcPdIVezyCyihoDFMernw44IKIqrjMsuJ0GbOSqeOTbKnsjLW/aNBj3r+jlnokS4OLRPEyFfCYyjEj8683Qqi3ElAAMDAHNS7YB9oK1nWd3w4FclHaATtBsE5CWquf6oli0jz58/0WxEyfcojEUYb2/4UQK+1w3W6oyQG9vO6wdPOh5gsotvJGEH7sMGeSVoVSdBgeYxlu1oGEoYObagOkaJfxhCON2BmhlMez8r+wcvtNYT930tfSXfmr9uToNzxkv45ltphbnLeIx/DrmaMEUOllzjQvvyN3ycJjtZKVP/dneCEpfziA98XpbRLPWGcFlPH8rZ53fAhAmUoHKZ9D7owrMx+h+BDU9YQso2cJOBruu3emPfy/clEWJeSr3cDLukcH/EaPw85KsVYhBvf4lsj3tZDfZ7RdkEyWtPcKMDc1PikabOHgETvXyBy+QMTe4rffRnlJypaBMzWiefiJ8MoyhJeKQcv0L5RCzXsTkHf3vtR4NyajM0mdJN5KwcjqLIoFDnv1+MhMnHpAweEUJh4nHLtNVJ3Irzq+A9cNMrsGWoDKYXUh53HFoDqexRf9dOhustp7pGazIgrhUDUyBlvpWnegvcSd57VavEswGpevii6D6o/3CNS+Qceo74J/e+7sbeG70Gnvuz1Y6BaG+SsxtUGU/FmGDjKSbQ=
# Required for lock file generation
# https://github.com/greenkeeperio/greenkeeper-lockfile
before_install: yarn global add greenkeeper-lockfile@1
before_script: 
  - greenkeeper-lockfile-update
  - yarn global add wait-port
  - yarn storybook & wait-port -t 10000 localhost:9002
after_script: greenkeeper-lockfile-upload
