version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/repo
    steps:
      # Fetch Code
      - checkout

      - restore_cache:
          keys:
            # Restore cached node_modules
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          keys:
            # Restore cached website node_modules
            - v1-website-dependencies-{{ checksum "website/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-website-dependencies-

      - run:
          name: Add CI global modules
          command: yarn global add greenkeeper-lockfile@1

      - run:
          name: Install Dependencies
          command: yarn

      - run: 
          name: Update Lockfile
          command: $(yarn global bin)/greenkeeper-lockfile-update

      - run:
          name: Upload Lockfile
          command: $(yarn global bin)/greenkeeper-lockfile-upload

      - run:
          name: Validate Yarn Lock File
          command: |
            if [[ "$(git status -s)" != "" ]] && [[ "$CIRCLE_BRANCH" != greenkeeper/* ]]; then
              echo "Your yarn.lock was modified during install, please check in any changes to the yarn.lock file"
              exit 1
            fi

      # Save the node_modules cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - website/node_modules
          key: v1-website-dependencies-{{ checksum "website/yarn.lock" }}
  validate:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - restore_cache:
          keys:
            - v1-website-dependencies-{{ checksum "website/yarn.lock" }}

      - run:
          # PR's from forks cannot use the dependency cache for performance reasons
          name: 'Forked PR dependency install'
          command: yarn

      - run:
          name: Lint + Typecheck
          command: yarn validate
  test:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - restore_cache:
          keys:
            - v1-website-dependencies-{{ checksum "website/yarn.lock" }}

      - run:
          # PR's from forks cannot use the dependency cache for performance reasons
          name: 'Forked PR dependency install'
          command: yarn

      - run:
          name: Jest Suite
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: 'test-reports/junit/js-test-results.xml'

      - store_test_results:
          path: test-reports/junit

      - run:
          name: Browser Suite
          command: node browser-test-harness.js yarn test:browser

      - store_test_results:
          path: test-reports/browser

      - store_artifacts:
          path: .storybook-out
          destination: storybook-out
  bundle-test:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - restore_cache:
          keys:
            - v1-website-dependencies-{{ checksum "website/yarn.lock" }}

      - run:
          # PR's from forks cannot use the dependency cache for performance reasons
          name: 'Forked PR dependency install'
          command: yarn

      - run:
          name: Check Bundle Size
          command: yarn run bundle-size:check

workflows:
  version: 2
  build:
    jobs:
      - install
      - validate:
          requires:
            - install
      - test:
          requires:
            - install
      - bundle-test:
          requires:
            - install
